# This is an example TOML configuration file. It is used to test the wflow configuration
# features, and can also be used to work towards an example of what we want the
# configuration file to look like.
# Relative file paths are interpreted as being relative to this TOML file.
# TOML documentation: https://github.com/toml-lang/toml

casename = "wflow_sbm"

calendar = "proleptic_gregorian"
starttime = 2010-02-01T00:00:00
endtime = 2010-02-10T00:00:00
time_units = "days since 1900-01-01 00:00:00"
timestepsecs = 86400
dir_output = "run_default"

[state]
path_input = "instate/instates.nc"
path_output = "outstate/outstates.nc"

# if listed, the variable must be present in the NetCDF or error
# if not listed, the variable can get a default value if it has one

[state.vertical]
satwaterdepth = "satwaterdepth"
snow = "snow"
tsoil = "tsoil"
ustorelayerdepth = "ustorelayerdepth"
snowwater = "snowwater"
canopystorage = "canopystorage"

[state.lateral.river]
q = "q_river"
h = "h_river"
h_av = "h_av_river"

[state.lateral.subsurface]
ssf = "ssf"

[state.lateral.land]
q = "q_land"
h = "h_land"
h_av = "h_av_land"

[input]
path_forcing = "inmaps.nc"
path_static = "staticmaps.nc"

# these are not directly part of the model
ldd = "wflow_ldd"
river_location = "wflow_river"
subcatchment = "wflow_subcatch"

# specify the internal IDs of the parameters which vary over time
# the external name mapping needs to be below together with the other mappings
forcing = [
  "vertical.precipitation",
  "vertical.temperature",
  "vertical.potential_evaporation",
]

cyclic = ["vertical.leaf_area_index"]

[input.vertical]
altitude = "wflow_dem"
c = "c"
cf_soil = "cf_soil"
cfmax = "Cfmax"
e_r = "EoverR"
f = "f"
infiltcappath = "InfiltCapPath"
infiltcapsoil = "InfiltCapSoil"
kext = "Kext"
kv_0 = "KsatVer"
leaf_area_index = "LAI" # TODO support cyclic
m = "M_"
maxleakage = "MaxLeakage"
pathfrac = "PathFrac"
potential_evaporation = "pet" # forcing
precipitation = "precip" # forcing
rootdistpar = "rootdistpar"
rootingdepth = "RootingDepth"
soilminthickness = "SoilMinThickness"
soilthickness = "SoilThickness"
specific_leaf = "Sl"
storage_wood = "Swood"
temperature = "temp" # forcing
tt = "TT"
tti = "TTI"
ttm = "TTM"
water_holding_capacity = "WHC"
waterfrac = "WaterFrac"
theta_s = "thetaS"
theta_r = "thetaR"

[input.lateral.river]
length = "wflow_riverlength"
n = "N_River"
slope = "RiverSlope"
width = "wflow_riverwidth"

[input.lateral.subsurface]
ksathorfrac = "KsatHorFrac"

[input.lateral.land]
n = "N"
slope = "Slope"

[model]
type = "sbm"
masswasting = true
snow = true
reinit = true
reservoirs = false
lakes = false
glacier = false

# Enable iterations of the kinematic wave
kin_wave_iteration = true
# Fixed sub-timestep for iterations of channel flow (river cells)
kw_river_tstep = 900
# Fixed sub-timestep for iterations of overland flow (land cells)
kw_land_tstep = 3600

thicknesslayers = [100, 300, 800]

[output]
path = "output.nc"

[output.lateral.river]
q_av = "q_river"

[csv]
path = "output.csv"
